# Generated by Django 5.2.9 on 2026-03-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_driver_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_driver_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='driver_verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
