# Generated by Django 5.2.9 on 2026-03-18 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255)),
                ('destination_name', models.CharField(max_length=255)),
                ('origin_coords', models.JSONField(blank=True, default=dict)),
                ('destination_coords', models.JSONField(blank=True, default=dict)),
                ('departure_time', models.DateTimeField()),
                ('total_seats', models.PositiveIntegerField(default=1)),
                ('available_seats', models.PositiveIntegerField(default=1)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
    ]
