# Generated by Django 5.2.9 on 2026-03-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='instant_book',
            field=models.BooleanField(default=False),
        ),
    ]
