# Generated by Django 5.2.9 on 2026-03-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_instant_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
